//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseActual
    {
        public int baseActualId { get; set; }
        public int BaseInfoId { get; set; }
        public System.DateTime updateTime { get; set; }
        public string key { get; set; }
        public string attr { get; set; }
        public Nullable<decimal> value { get; set; }
        public int baseTypeId { get; set; }
        public string valueStr { get; set; }
    
        public virtual BaseInfo BaseInfo { get; set; }
        public virtual BaseType BaseType { get; set; }
    }
}
