//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseInfo()
        {
            this.BaseActual = new HashSet<BaseActual>();
            this.BaseHistorical = new HashSet<BaseHistorical>();
            this.BasePolicy = new HashSet<BasePolicy>();
        }
    
        public int baseInfoId { get; set; }
        public int baseTypeId { get; set; }
        public string baseName { get; set; }
        public int foreachSourceId { get; set; }
        public int beformSourceId { get; set; }
        public bool isActual { get; set; }
        public int status { get; set; }
        public string description { get; set; }
        public string foreachParam { get; set; }
        public string beform { get; set; }
        public string before { get; set; }
        public string token { get; set; }
        public string refererUrl { get; set; }
        public System.DateTime createTime { get; set; }
        public int handleId { get; set; }
        public Nullable<System.DateTime> openTime { get; set; }
        public string openResult { get; set; }
        public int restartCount { get; set; }
        public int valueType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseActual> BaseActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseHistorical> BaseHistorical { get; set; }
        public virtual BaseType BaseType { get; set; }
        public virtual DataSource DataSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasePolicy> BasePolicy { get; set; }
    }
}
