//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasePolicy
    {
        public int Id { get; set; }
        public int baseInfoId { get; set; }
        public int policyId { get; set; }
    
        public virtual BaseInfo BaseInfo { get; set; }
        public virtual TriggerPolicy TriggerPolicy { get; set; }
    }
}
