//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataResult
    {
        public int dataResultId { get; set; }
        public int dataFormulaId { get; set; }
        public System.DateTime createTime { get; set; }
        public System.DateTime historicalDate { get; set; }
        public string key { get; set; }
        public string attr { get; set; }
        public decimal value { get; set; }
        public string formulaCode { get; set; }
        public string process { get; set; }
    
        public virtual DataFormula DataFormula { get; set; }
    }
}
