//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskManagementTestEntities : DbContext
    {
        public TaskManagementTestEntities()
            : base("name=TaskManagementTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationType> ApplicationType { get; set; }
        public virtual DbSet<BaseActual> BaseActual { get; set; }
        public virtual DbSet<BaseHistorical> BaseHistorical { get; set; }
        public virtual DbSet<BaseInfo> BaseInfo { get; set; }
        public virtual DbSet<BasePolicy> BasePolicy { get; set; }
        public virtual DbSet<BaseType> BaseType { get; set; }
        public virtual DbSet<DataFormula> DataFormula { get; set; }
        public virtual DbSet<DataResult> DataResult { get; set; }
        public virtual DbSet<DataSource> DataSource { get; set; }
        public virtual DbSet<FormulaPolicy> FormulaPolicy { get; set; }
        public virtual DbSet<FormulaType> FormulaType { get; set; }
        public virtual DbSet<MonitorPolicy> MonitorPolicy { get; set; }
        public virtual DbSet<PolicyType> PolicyType { get; set; }
        public virtual DbSet<SourceHandle> SourceHandle { get; set; }
        public virtual DbSet<SourceType> SourceType { get; set; }
        public virtual DbSet<TaskApplication> TaskApplication { get; set; }
        public virtual DbSet<TaskManualState> TaskManualState { get; set; }
        public virtual DbSet<TaskRefreshTime> TaskRefreshTime { get; set; }
        public virtual DbSet<TriggerPolicy> TriggerPolicy { get; set; }
    }
}
