//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataFormula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataFormula()
        {
            this.DataResult = new HashSet<DataResult>();
            this.FormulaPolicy = new HashSet<FormulaPolicy>();
        }
    
        public int dataFormulaId { get; set; }
        public int formulaTypeId { get; set; }
        public string formula { get; set; }
        public string formulaCode { get; set; }
        public string description { get; set; }
        public int status { get; set; }
        public string formulaRemark { get; set; }
        public string otherRemark { get; set; }
        public double sort { get; set; }
        public System.DateTime createTime { get; set; }
    
        public virtual FormulaType FormulaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataResult> DataResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaPolicy> FormulaPolicy { get; set; }
    }
}
