//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceHandle
    {
        public int sourceHandleId { get; set; }
        public int sourceTypeId { get; set; }
        public string handleInfo { get; set; }
        public string interfaceInfo { get; set; }
        public string interfaceNumber { get; set; }
    
        public virtual SourceType SourceType { get; set; }
    }
}
