//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskApplication()
        {
            this.TaskManualState = new HashSet<TaskManualState>();
        }
    
        public int appId { get; set; }
        public string appTitle { get; set; }
        public int appTypeID { get; set; }
        public string appPath { get; set; }
        public string appParamKey { get; set; }
        public string appParamType { get; set; }
        public string appParamVlue { get; set; }
        public int policyId { get; set; }
        public string isProtect { get; set; }
        public double appSort { get; set; }
        public string preopen { get; set; }
        public Nullable<System.DateTime> openTime { get; set; }
        public string openResult { get; set; }
        public System.DateTime createTime { get; set; }
        public string remark { get; set; }
        public string token { get; set; }
        public string refererUrl { get; set; }
        public int appState { get; set; }
        public int isKept { get; set; }
        public int restartCount { get; set; }
    
        public virtual ApplicationType ApplicationType { get; set; }
        public virtual TriggerPolicy TriggerPolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskManualState> TaskManualState { get; set; }
    }
}
