//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TriggerPolicy()
        {
            this.BasePolicy = new HashSet<BasePolicy>();
            this.FormulaPolicy = new HashSet<FormulaPolicy>();
            this.TaskApplication = new HashSet<TaskApplication>();
        }
    
        public int policyId { get; set; }
        public string policyName { get; set; }
        public int policyTypeId { get; set; }
        public int taskSpace { get; set; }
        public int taskType { get; set; }
        public string dateList { get; set; }
        public int dateSpace { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string remark { get; set; }
        public bool excludeHoliday { get; set; }
        public int restartCount { get; set; }
        public int restartSpace { get; set; }
        public int state { get; set; }
        public System.DateTime createTime { get; set; }
        public string dayList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasePolicy> BasePolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaPolicy> FormulaPolicy { get; set; }
        public virtual PolicyType PolicyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskApplication> TaskApplication { get; set; }
    }
}
